inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

Layout/LineLength:
  IgnoreCopDirectives: true
  Max: 107

Metrics/BlockLength:
  Exclude:
    - sports.gemspec
    - db/schema.rb
    - test/dummy/db/schema.rb

Style/Documentation:
  Enabled: false

