#!/bin/bash
#
# sportsmistress      Startup script for the sportsmistress application
#
# chkconfig: 345 88 12
# description: SportsMistress

# See how we were called.
case "$1" in
  start)
        mongrel_rails start -p 3007 -e production -c /u/apps/sportsmistress/current -d 1>/u/apps/sportsmistress/shared/log/stdout.log 2>/u/apps/sportsmistress/shared/log/stderr.log
        ;;
  stop)
        mongrel_rails stop -c /u/apps/sportsmistress/current
        ;;
  restart)
        mongrel_rails restart -c /u/apps/sportsmistress/current
        ;;
  status)
        ps -ef | grep sportsmistress
        ;;
  *)
        echo $"Usage: $prog {start|stop|restart|status}"
        exit 1
esac

exit 0
