# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "tours", :force => true do |t|
    t.column "started_at",    :datetime,                               :null => false
    t.column "total_time",    :time,                                   :null => false
    t.column "distance",      :decimal,  :precision => 6, :scale => 2, :null => false
    t.column "average_speed", :decimal,  :precision => 4, :scale => 1, :null => false
    t.column "max_speed",     :decimal,  :precision => 4, :scale => 1, :null => false
    t.column "calories",      :decimal,  :precision => 5, :scale => 1, :null => false
    t.column "odo",           :decimal,  :precision => 7, :scale => 1, :null => false
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
  end

end
